name: Docker Build
on: [push, workflow_dispatch]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: false
          tags: myapp:test-${{ github.sha }}
